
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      + meson setup C:\Users\jessi\AppData\Local\Temp\pip-install-6a6dzubm\matplotlib_4737d3776daf4dc2834f87f0a51f08cc C:\Users\jessi\AppData\Local\Temp\pip-install-6a6dzubm\matplotlib_4737d3776daf4dc2834f87f0a51f08cc\.mesonpy-keyao12r -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\jessi\AppData\Local\Temp\pip-install-6a6dzubm\matplotlib_4737d3776daf4dc2834f87f0a51f08cc\.mesonpy-keyao12r\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: C:\Users\jessi\AppData\Local\Temp\pip-install-6a6dzubm\matplotlib_4737d3776daf4dc2834f87f0a51f08cc
      Build dir: C:\Users\jessi\AppData\Local\Temp\pip-install-6a6dzubm\matplotlib_4737d3776daf4dc2834f87f0a51f08cc\.mesonpy-keyao12r
      Build type: native build
      Program python3 found: YES (C:\Users\jessi\.pyenv\pyenv-win\shims\python3.BAT)

      ..\meson.build:4:11: ERROR: Command `C:\Users\jessi\.pyenv\pyenv-win\shims\python3.BAT -m setuptools_scm` failed with status 1.

      A full log can be found at C:\Users\jessi\AppData\Local\Temp\pip-install-6a6dzubm\matplotlib_4737d3776daf4dc2834f87f0a51f08cc\.mesonpy-keyao12r\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(synthesis) C:\Users\jessi>